const CATEGORY_CONFIG={
 news:{title:'الأخبار',icon:'📰',description:'آخر أخبار ونشاطات فريق شمال واسط.',collection:'news'},
 events:{title:'الفعاليات',icon:'📅',description:'الفعاليات والمبادرات القادمة والسابقة.',collection:'events'},
 articles:{title:'المقالات',icon:'📚',description:'مقالات ومواضيع معرفية ومجتمعية.',collection:'articles'},
 health:{title:'الصحة',icon:'🩺',description:'محتوى صحي وتوعوي موثوق.',collection:'health'},
 environment:{title:'البيئة',icon:'🌱',description:'مبادرات وأفكار لحماية بيئتنا.',collection:'environment'}
};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function postCard(d,id){const title=esc(d.title||'منشور بدون عنوان'),body=esc(d.content||d.body||'');let date='';if(d.createdAt?.toDate) date=d.createdAt.toDate().toLocaleDateString('ar-IQ');else if(d.date) date=esc(d.date);return `<article class="post-card">${d.imageUrl?`<img src="${esc(d.imageUrl)}" alt="" loading="lazy">`:''}<div class="post-body"><div class="post-meta">${date||'فريق شمال واسط'}</div><h3>${title}</h3><p>${body}</p></div></article>`;}
async function loadCategoryPage(key,limit=null){const cfg=CATEGORY_CONFIG[key];if(!cfg)return;const el=document.getElementById('posts');el.innerHTML='<div class="empty-state">جاري تحميل المنشورات...</div>';try{let q=db.collection(cfg.collection).orderBy('createdAt','desc');if(limit)q=q.limit(limit);const snap=await q.get();if(snap.empty){el.innerHTML='<div class="empty-state">لا توجد منشورات حاليًا</div>';return;}el.innerHTML=snap.docs.map(x=>postCard(x.data(),x.id)).join('');}catch(e){console.error(e);el.innerHTML='<div class="empty-state">تعذر تحميل المنشورات حاليًا.</div>';}}
async function loadHomeFeeds(){for(const key of Object.keys(CATEGORY_CONFIG)){const box=document.querySelector(`[data-feed="${key}"]`);if(!box)continue;try{const snap=await db.collection(CATEGORY_CONFIG[key].collection).orderBy('createdAt','desc').limit(3).get();box.innerHTML=snap.empty?'<div class="empty-state">لا توجد منشورات حاليًا</div>':snap.docs.map(x=>postCard(x.data(),x.id)).join('');}catch(e){console.error(e);box.innerHTML='<div class="empty-state">تعذر تحميل المنشورات.</div>';}}}